# Generated by Django 3.1.7 on 2021-04-03 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('type', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('rdate', models.DateField()),
                ('language', models.CharField(max_length=255)),
                ('cover', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sequal', models.CharField(max_length=255)),
                ('trailer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('profile_pic', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('ndate', models.DateTimeField(auto_now_add=True)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PredixWeb.movies')),
            ],
        ),
        migrations.CreateModel(
            name='MyMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PredixWeb.movies')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PredixWeb.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PredixWeb.movies')),
            ],
        ),
    ]
