# Generated by Django 3.1.7 on 2021-04-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PredixWeb', '0002_auto_20210417_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='mid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
