# Generated by Django 3.1.7 on 2021-04-18 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PredixWeb', '0006_auto_20210417_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gender',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
