# Generated by Django 3.1.7 on 2021-04-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PredixWeb', '0007_auto_20210418_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymovies',
            name='uid',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
