# Generated by Django 3.1.7 on 2021-04-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PredixWeb', '0009_mymovies_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymovies',
            name='watched',
            field=models.BooleanField(),
        ),
    ]
