# Generated by Django 3.1.7 on 2021-04-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PredixWeb', '0011_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
